version: '3'
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data:/updater/data
    environment:
      - DELAY=300
      - ROOTURL=
      - LISTENINGPORT=8000
      - LOGGING=human
      - NODEID=0
    restart: always
